---
- hosts: builder
  gather_facts: no
  become: true
  vars:
      http_repo: true
  pre_tasks:        
    - name: install packages
      apt:
        name: "{{ item }}"
      loop:
        - curl
        - wget
        - make
        - gcc
        - git
        - gzip
        - dpkg-dev
      
    - name: Check if libssl has build
      stat:
        path: "{{ build_dir }}/libssl/{{ libssl_ver }}/crypto/.libs/libcrypto.a"
      register: libssl_buld

  roles:
      - role: libssl   # build libssl
        when: not libssl_buld.stat.exists

      - role: peervpn  # build peervpn bin

      - role: repo
        when: http_repo
        tags: 
          - repo
      
  post_tasks: 
    - name: add peervpn repo
      apt_repository:
        filename: peervpn
        repo: "deb [trusted=yes] http://127.0.0.1/peervpn ./"
          
    - name: install peervpn
      apt:
        name: "peervpn"
        update_cache: yes