---    
- name: "repo | Allow all access to tcp port 80"
  ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: "repo | install Nginx"
  apt:
    name: "nginx"

- name: "repo | Create a directory if it does not exist"
  file:
    path: "{{ repo_dir }}/peervpn"
    state: directory
    mode: 0755
    owner: www-data
    group: www-data

- name: "repo | Nginx config template"
  template:
    src: 'nginx.conf.j2'
    dest: '/etc/nginx/nginx.conf'
  notify: Reload Nginx

- name: "repo | Start service Nginx"
  ansible.builtin.service:
    name: nginx
    state: started

- name: "repo | Copy deb to repo struct"
  copy:
    src: "{{ build_dir }}/deb/peervpn_{{ peervpn_ver }}.deb"
    dest: "{{ repo_dir }}/peervpn/"
    remote_src: yes
  register: deb

- name: "repo | Buld"
  shell:
    cmd: "cd {{ repo_dir }}/peervpn && dpkg-scanpackages . | gzip -c9  > Packages.gz" 
  when: deb.changed